import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { motion } from "framer-motion";

const PrivacyPolicy = () => {
  const motionProps = {
    initial: { opacity: 0, y: 20 },
    whileInView: { opacity: 1, y: 0 },
    viewport: { once: true, amount: 0.1 },
    transition: { duration: 0.5 }
  };

  return (
    <Card className="w-full max-w-4xl text-white bg-black/20 border-gray-800 backdrop-blur-sm">
      <CardHeader>
        <CardTitle>Privacy Policy</CardTitle>
      </CardHeader>
      <CardContent className="prose prose-lg prose-invert text-left max-w-none prose-p:text-gray-300 prose-headings:text-white prose-headings:font-normal prose-ul:text-gray-300">
        <motion.div {...motionProps}>
          <p>Last updated: October 1, 2025</p>
          <p>Paulify Development ("we", "our", "us") operates the open-source application Tagthem.app. We are committed to protecting your privacy and complying with the EU General Data Protection Regulation (GDPR).</p>
        </motion.div>

        <motion.div {...motionProps} transition={{ ...motionProps.transition, delay: 0.05 }} className="space-y-4 mt-8">
          <h2>1. Data Collection</h2>
          <p>When using Tagthem.app, you may be asked to provide the following information:</p>
          <ul>
            <li>Name</li>
            <li>Email address</li>
            <li>Phone number</li>
          </ul>
          <p>This data is required in order to generate tags, link them to QR codes or NFC tags, and provide the intended functionality of the App.</p>
        </motion.div>

        <motion.div {...motionProps} transition={{ ...motionProps.transition, delay: 0.1 }} className="space-y-4 mt-8">
          <h2>2. Data Usage</h2>
          <p>The personal information you provide will only be used to operate and maintain the functionality of Tagthem.app.</p>
          <p>We do not share or sell your personal information to third parties.</p>
          <p>By using the App, you accept that the usage of generated tags and their distribution is your own responsibility.</p>
        </motion.div>

        <motion.div {...motionProps} transition={{ ...motionProps.transition, delay: 0.15 }} className="space-y-4 mt-8">
          <h2>3. Data Storage & Security</h2>
          <p>All data is securely stored in a protected SQL database.</p>
          <p>We apply appropriate technical and organizational measures to ensure the safety of your data.</p>
        </motion.div>

        <motion.div {...motionProps} transition={{ ...motionProps.transition, delay: 0.2 }} className="space-y-4 mt-8">
          <h2>4. Consent & Responsibility</h2>
          <p>By using the App, you consent to the processing and storage of your personal data as described in this Privacy Policy.</p>
          <p>The use of tags, QR codes, or NFC tags generated by the App is entirely at your own responsibility.</p>
        </motion.div>

        <motion.div {...motionProps} transition={{ ...motionProps.transition, delay: 0.25 }} className="space-y-4 mt-8">
          <h2>5. Legal Basis (GDPR)</h2>
          <p>The processing of personal data is based on:</p>
          <ul>
            <li>Art. 6(1)(b) GDPR (performance of a contract)</li>
            <li>Art. 6(1)(a) GDPR (consent)</li>
          </ul>
        </motion.div>

        <motion.div {...motionProps} transition={{ ...motionProps.transition, delay: 0.3 }} className="space-y-4 mt-8">
          <h2>6. Data Retention</h2>
          <p>We will store your personal data for as long as it is necessary to provide the service. Data will be deleted once it is no longer required or upon your request, unless legal obligations require retention.</p>
        </motion.div>

        <motion.div {...motionProps} transition={{ ...motionProps.transition, delay: 0.35 }} className="space-y-4 mt-8">
          <h2>7. Your Rights under GDPR</h2>
          <p>You have the right to:</p>
          <ul>
            <li>Access your personal data (Art. 15 GDPR)</li>
            <li>Correct inaccurate data (Art. 16 GDPR)</li>
            <li>Request deletion (Art. 17 GDPR)</li>
            <li>Restrict processing (Art. 18 GDPR)</li>
            <li>Data portability (Art. 20 GDPR)</li>
            <li>Withdraw consent at any time (Art. 7(3) GDPR)</li>
          </ul>
          <p>To exercise your rights, please contact: contact@paulify.cc</p>
        </motion.div>

        <motion.div {...motionProps} transition={{ ...motionProps.transition, delay: 0.4 }} className="space-y-4 mt-8">
          <h2>8. Open Source Notice</h2>
          <p>Tagthem.app is open source. Contributions (e.g., on GitHub) may be publicly visible and are subject to the respective platform’s privacy policies.</p>
        </motion.div>

        <motion.div {...motionProps} transition={{ ...motionProps.transition, delay: 0.45 }} className="space-y-4 mt-8">
          <h2>9. Contact</h2>
          <p>
            Paulify Development<br />
            Email: contact@paulify.cc
          </p>
          <p>Website: <a href="https://paulify.eu" target="_blank" rel="noopener noreferrer">https://paulify.eu</a></p>
        </motion.div>
      </CardContent>
    </Card>
  );
};

export default PrivacyPolicy;