// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xdxnqnbayshfkbnzstzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkeG5xbmJheXNoZmtibnpzdHp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NzU2NDksImV4cCI6MjA3MzM1MTY0OX0.9z6IY7vmNXf6DFH_cXcY-2awGzMJ5OZ716yzVs-fnRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);